import tkinter as tk 
from tkinter import *
window = tk.Tk()
window.title("T-Town Veterinary Database ")
label1 = tk.Label(window,text="Client Database")
label1.grid(row = 1, column = 2)
dogphoto = PhotoImage(file="dog.png")
label2 = tk.Label(window, image=dogphoto, borderwidth=3)
label2.grid(row = 1, column = 1)
entry1 = tk.Entry(window, borderwidth=3,text="Name")
entry1.grid(row=3, column = 0)
entry2 = tk.Entry(window, borderwidth=3,text="Type")
entry2.grid(row=3, column = 1)
entry3 = tk.Entry(window, borderwidth=3,text="Breed")
entry3.grid(row=3, column = 2)
entry4 = tk.Entry(window, borderwidth=3,text="Owner")
entry4.grid(row=3, column = 3)
entry5 = tk.Entry(window, borderwidth=3,text="Birthdate")
entry5.grid(row=3, column = 4)
button1 = tk.Button(window,text="Clash Royale")
button1.grid(row = 4, column = 2)
button2 = tk.Button(window,text="<Previous")
button2.grid(row = 4, column = 0)
button3 = tk.Button(window,text="Next>")
button3.grid(row = 4, column = 4)
label3 = tk.Label(window,text="Text that does\nnothing is a label", bg="#ee0000")
window.mainloop()